//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HostManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // ===== Window Titles =====
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "Host Manager";
        public static string GuideTitle => ResourceManager.GetString("GuideTitle", resourceCulture) ?? "User Guide";
        public static string ExitTitle => ResourceManager.GetString("ExitTitle", resourceCulture) ?? "Exit Program";
        public static string AddHostTitle => ResourceManager.GetString("AddHostTitle", resourceCulture) ?? "Add Host";
        public static string EnvManageTitle => ResourceManager.GetString("EnvManageTitle", resourceCulture) ?? "Environment Management";
        public static string GroupManageTitle => ResourceManager.GetString("GroupManageTitle", resourceCulture) ?? "Group Management";
        
        // ===== Buttons =====
        public static string Refresh => ResourceManager.GetString("Refresh", resourceCulture) ?? "Refresh";
        public static string Save => ResourceManager.GetString("Save", resourceCulture) ?? "Save";
        public static string Add => ResourceManager.GetString("Add", resourceCulture) ?? "Add";
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture) ?? "Delete";
        public static string Enable => ResourceManager.GetString("Enable", resourceCulture) ?? "Enable";
        public static string Disable => ResourceManager.GetString("Disable", resourceCulture) ?? "Disable";
        public static string SelectAll => ResourceManager.GetString("SelectAll", resourceCulture) ?? "Select All/None";
        public static string Open => ResourceManager.GetString("Open", resourceCulture) ?? "OPEN";
        public static string Backup => ResourceManager.GetString("Backup", resourceCulture) ?? "Backup";
        public static string Guide => ResourceManager.GetString("Guide", resourceCulture) ?? "Guide";
        public static string Ok => ResourceManager.GetString("Ok", resourceCulture) ?? "OK";
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "Cancel";
        public static string Yes => ResourceManager.GetString("Yes", resourceCulture) ?? "Yes";
        public static string No => ResourceManager.GetString("No", resourceCulture) ?? "No";
        public static string Close => ResourceManager.GetString("Close", resourceCulture) ?? "Close";
        public static string Confirm => ResourceManager.GetString("Confirm", resourceCulture) ?? "Confirm";
        public static string Reset => ResourceManager.GetString("Reset", resourceCulture) ?? "Reset";
        
        // ===== Labels =====
        public static string Environment => ResourceManager.GetString("Environment", resourceCulture) ?? "Environment";
        public static string Group => ResourceManager.GetString("Group", resourceCulture) ?? "Group";
        public static string Search => ResourceManager.GetString("Search", resourceCulture) ?? "Search";
        public static string All => ResourceManager.GetString("All", resourceCulture) ?? "All";
        public static string None => ResourceManager.GetString("None", resourceCulture) ?? "None";
        public static string IpAddress => ResourceManager.GetString("IpAddress", resourceCulture) ?? "IP Address";
        public static string HostName => ResourceManager.GetString("HostName", resourceCulture) ?? "Host Name";
        public static string Description => ResourceManager.GetString("Description", resourceCulture) ?? "Description";
        public static string Enabled => ResourceManager.GetString("Enabled", resourceCulture) ?? "Enabled";
        public static string Select => ResourceManager.GetString("Select", resourceCulture) ?? "Select";
        public static string Unspecified => ResourceManager.GetString("Unspecified", resourceCulture) ?? "Unspecified";
        
        // ===== Exit Dialog =====
        public static string ExitProgram => ResourceManager.GetString("ExitProgram", resourceCulture) ?? "Exit Program";
        public static string MinimizeToTray => ResourceManager.GetString("MinimizeToTray", resourceCulture) ?? "Minimize to Tray";
        public static string ExitQuestion => ResourceManager.GetString("ExitQuestion", resourceCulture) ?? "Do you want to exit the program?";
        public static string TrayDescription => ResourceManager.GetString("TrayDescription", resourceCulture) ?? "Minimizing to system tray will keep the program running in the background.";
        
        // ===== Messages =====
        public static string SaveSuccess => ResourceManager.GetString("SaveSuccess", resourceCulture) ?? "Saved successfully.";
        public static string SaveFailed => ResourceManager.GetString("SaveFailed", resourceCulture) ?? "Failed to save.";
        public static string BackupSuccess => ResourceManager.GetString("BackupSuccess", resourceCulture) ?? "Backup completed.";
        public static string BackupFailed => ResourceManager.GetString("BackupFailed", resourceCulture) ?? "Backup failed.";
        public static string DeleteConfirm => ResourceManager.GetString("DeleteConfirm", resourceCulture) ?? "Are you sure you want to delete the selected items?";
        public static string SelectItemToDelete => ResourceManager.GetString("SelectItemToDelete", resourceCulture) ?? "Please select items to delete.";
        public static string SelectItemToEnable => ResourceManager.GetString("SelectItemToEnable", resourceCulture) ?? "Please select items to enable.";
        public static string SelectItemToDisable => ResourceManager.GetString("SelectItemToDisable", resourceCulture) ?? "Please select items to disable.";
        public static string InvalidIpAddress => ResourceManager.GetString("InvalidIpAddress", resourceCulture) ?? "Please enter a valid IP address.";
        public static string InvalidHostName => ResourceManager.GetString("InvalidHostName", resourceCulture) ?? "Please enter a valid host name.";
        public static string AdminRequired => ResourceManager.GetString("AdminRequired", resourceCulture) ?? "Please run the program as administrator.";
        public static string UnsavedChanges => ResourceManager.GetString("UnsavedChanges", resourceCulture) ?? "There are unsaved changes. Do you want to save?";
        public static string HostsFileNotFound => ResourceManager.GetString("HostsFileNotFound", resourceCulture) ?? "Hosts file not found.";
        public static string Error => ResourceManager.GetString("Error", resourceCulture) ?? "Error";
        public static string Warning => ResourceManager.GetString("Warning", resourceCulture) ?? "Warning";
        public static string Info => ResourceManager.GetString("Info", resourceCulture) ?? "Information";
        public static string Success => ResourceManager.GetString("Success", resourceCulture) ?? "Success";
        public static string PermissionError => ResourceManager.GetString("PermissionError", resourceCulture) ?? "Permission Error";
        public static string InputError => ResourceManager.GetString("InputError", resourceCulture) ?? "Input Error";
        public static string DeleteConfirmTitle => ResourceManager.GetString("DeleteConfirmTitle", resourceCulture) ?? "Delete Confirmation";
        public static string SaveConfirmTitle => ResourceManager.GetString("SaveConfirmTitle", resourceCulture) ?? "Save Confirmation";
        public static string BackupFile => ResourceManager.GetString("BackupFile", resourceCulture) ?? "Backup file";
        
        // ===== Tooltips =====
        public static string RefreshTooltip => ResourceManager.GetString("RefreshTooltip", resourceCulture) ?? "Ctrl+R or F5";
        public static string SaveTooltip => ResourceManager.GetString("SaveTooltip", resourceCulture) ?? "Ctrl+S";
        public static string AddTooltip => ResourceManager.GetString("AddTooltip", resourceCulture) ?? "Ctrl+N";
        public static string DeleteTooltip => ResourceManager.GetString("DeleteTooltip", resourceCulture) ?? "Delete";
        public static string SelectAllTooltip => ResourceManager.GetString("SelectAllTooltip", resourceCulture) ?? "Ctrl+A";
        public static string OpenTooltip => ResourceManager.GetString("OpenTooltip", resourceCulture) ?? "Open hosts file";
        public static string BackupTooltip => ResourceManager.GetString("BackupTooltip", resourceCulture) ?? "Backup hosts file";
        public static string GuideTooltip => ResourceManager.GetString("GuideTooltip", resourceCulture) ?? "View user guide (Ctrl+H)";
        public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", resourceCulture) ?? "Search IP or hostname...";
        
        // ===== Tray =====
        public static string TrayOpen => ResourceManager.GetString("TrayOpen", resourceCulture) ?? "Open";
        public static string TrayExit => ResourceManager.GetString("TrayExit", resourceCulture) ?? "Exit";
        public static string TrayMinimized => ResourceManager.GetString("TrayMinimized", resourceCulture) ?? "Program minimized to system tray.";
        
        // ===== Add Host Dialog =====
        public static string NewHost => ResourceManager.GetString("NewHost", resourceCulture) ?? "New Host";
        
        // ===== Env/Group Management =====
        public static string EnvDeleteConfirm => ResourceManager.GetString("EnvDeleteConfirm", resourceCulture) ?? "Are you sure you want to delete environment '{0}'?\nHosts with this environment will have their environment removed.";
        public static string GroupDeleteConfirm => ResourceManager.GetString("GroupDeleteConfirm", resourceCulture) ?? "Are you sure you want to delete group '{0}'?\nHosts with this group will have their group removed.";
        public static string ManageEnv => ResourceManager.GetString("ManageEnv", resourceCulture) ?? "Manage";
        public static string ManageGroup => ResourceManager.GetString("ManageGroup", resourceCulture) ?? "Manage";
    }
}
